// <auto-generated />
namespace LeaveManagementApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LeaveRequestAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeaveRequestAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201911290515262_Leave Request Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
